Fetching favorites for user 8732352
Switching to API Credentials #8
Switching to API Credentials #0
Switching to API Credentials #1
Switching to API Credentials #2
Switching to API Credentials #3
Switching to API Credentials #4
Switching to API Credentials #5
Switching to API Credentials #6
Switching to API Credentials #7
Switching to API Credentials #8
Switching to API Credentials #0
Switching to API Credentials #1
Switching to API Credentials #2
Switching to API Credentials #3
Switching to API Credentials #4
Done. Took 11.7 secs to fetch 0 favs
Fetching timeline for user 178166167
Traceback (most recent call last):
  File "fetch_tls_onemoremonth.py", line 32, in <module>
    user.fetch_timeline(s)
  File "/home/dominguez/tesiscelayes/sna_classifier/tw_dataset/dbmodels.py", line 137, in fetch_timeline
    self.retweets = []
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1022, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1042, in _set_iterable
    old = self.get(state, dict_, passive=PASSIVE_ONLY_PERSISTENT)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = self.callable_(state, passive)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 529, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 599, in _emit_lazyload
    result = q.all()
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
    self.session._autoflush()
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1282, in _autoflush
    self.flush()
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 487, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 1090, in process_saves
    secondary_update, secondary_delete)
  File "/home/dominguez/tesiscelayes/tesisVENV/local/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 1111, in _run_crud
    result.rowcount)
sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 'users_timeline' expected to delete 272 row(s); Only 273 were matched.